### ISSUE TITLE
chrome plugin stopped working

### ISSUE THREAD

**Issue by donmaltito** [snowflake-analytics/chrome-snowplow-inspector#1]
The chrome plugin stopped working and I can't find a reason why. No matter how many snowplow events are triggered nothing shows up in the snowflake inspector. I reinstalled both chrome and the extension with no success. The tool is amazing and I really want it back ;)

![screen shot 2017-07-17 at 12 42 20](https://user-images.githubusercontent.com/30232183/28264904-6a62664a-6aed-11e7-94dc-96687a126098.png) Amazing screenshot, where you cannot see anything...

Chrome Version 59.0.3071.115 (Official Build) (64-bit)
Using Snowplow Inspector 0.1.4

**Comment by jethron** [comment]
Hey @donmaltito, does this still happen in 0.1.5? Could you post which site you're seeing this happen on, if possible?

**Comment by donmaltito** [comment]
It works now with 0.1.5, The issue was present on www.justwatch.com

Thanks for your support
