### ISSUE TITLE
Snapshot versions of schemas

### ISSUE THREAD

**Issue by kdallmeyer-sr** [snowflake-analytics/chrome-snowplow-inspector#11]
Hi Snowplow Extension Owners,

We would like to support pre-released SNAPSHOT versions into validator. Oftentimes, our engineers will want to develop their schemas alongside any frontend code they write. Until it is in production, the schema may be not finalized.  We want to release SNAPSHOT versions into our schema repository and use the snowplow extension to validate those schemas.

The format of the schema version would look something like `0-1-0-BRANCH-SNAPSHOT`.

This probably means updating the Regex at https://github.com/snowflake-analytics/chrome-snowplow-inspector/blob/ec53e19c5233da5595a1f2a3218a0f58c92a184e/src/validator.ts#L11
```typescript
const SCHEMA_PATTERN = /^iglu:([a-zA-Z0-9_.-]+)\/([a-zA-Z0-9_-]+)\/([a-zA-Z0-9_-]+)\/([1-9][0-9]*(?:-(?:0|[1-9][0-9]*)){2})$/;
```
to have `(?:-[a-zA-Z0-9_-]+)?` at the end to capture that SNAPSHOT tag.
```typescript
const SCHEMA_PATTERN = /^iglu:([a-zA-Z0-9_.-]+)\/([a-zA-Z0-9_-]+)\/([a-zA-Z0-9_-]+)\/([1-9][0-9]*(?:-(?:0|[1-9][0-9]*)){2}(?:-[a-zA-Z0-9_-]+)?)$/;
```

Interested to hear other thoughts.

**Comment by miike** [comment]
I think rather than changing the default behaviour at the moment which will only pass valid Iglu URIs we could add an option (default unchecked) in the settings to not validate schema versions.

[Schema versioning](https://github.com/snowplow/iglu/wiki/SchemaVer) doesn't accomodate starting a schema with 0 or adding additional text at the end of a schema so we wouldn't want to return this as valid unless the user explicitly opted in this behaviour. Thoughts @jethron?

**Comment by kdallmeyer-sr** [comment]
It turns out that even if I enable snapshots into the regex or disable schema checking as an option, the JSON Schema for self-describing schemas has regex that also enforcing the schema. I can add catch statement that ignores specific message. But I am not sure how to do that...

Where can I propose adding snapshot versions to SchemaVersion?

--------------------------
unstruct_event
```json
{
	"$schema": "http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#",
	"description": "Schema for a Snowplow unstructured event",
	"self": {
		"vendor": "com.snowplowanalytics.snowplow",
		"name": "unstruct_event",
		"format": "jsonschema",
		"version": "1-0-0"
	},
	"type": "object",
	"properties": {
		"schema": {
			"type": "string",
			"pattern": "^iglu:[a-zA-Z0-9-_.]+/[a-zA-Z0-9-_]+/[a-zA-Z0-9-_]+/[0-9]+-[0-9]+-[0-9]+$"
		},
		"data": {}
	},
	"required": ["schema", "data"],
	"additionalProperties": false	
}
```

**Comment by jethron** [comment]
Thanks for your PR @kdallmeyer-sr! 

I think the original pattern was from the enricher so I'm a bit surprised these events enrich properly to begin with.

I don't really have an environment to test this on, do you mind trying the build on ab57a76 and seeing if that helps make the validation work?

**Comment by miike** [comment]
Hi @kdallmeyer-sr the best place to discuss this is probably in https://github.com/snowplow/snowplow as making any change to SchemaVer would need to result in significant changes to almost all parts of the Snowplow pipeline (trackers, collectors, enrichers, data loaders and sinks etc).

**Comment by jethron** [comment]
I think the concept is more of an Iglu thing, so filing an issue with an RFC at https://github.com/snowplow/iglu/issues/ will be your best bet if you want SchemaVer changed.
