### ISSUE TITLE
How can we clear extension's cache

### ISSUE THREAD

**Issue by kdallmeyer-sr** [snowflake-analytics/chrome-snowplow-inspector#21]
We are trying to do development of a new schema or make changes to existing ones. Since the extension and Snowplow doesn't support SNAPSHOT versions, we are reloading our incomplete version multiple times into our static Iglu website.  We want to validate our changes using the extension but it appears the schema is cached.  How can we clear the cache manually so we can continue to do testing?

See how extension caches the schema here:
https://github.com/snowflake-analytics/chrome-snowplow-inspector/blob/master/src/validator.ts#L28

**Comment by jethron** [comment]
Thanks @kdallmeyer-sr, ef13d5a37 should add a button to the main toolbar to allow you to do this. It will be live shortly as part of v0.2.11 and roll out shortly today.
You might also be interested in the 'local schema' functionality introduced in v0.2.10, if you go into the extension settings you should be able to paste your JSON Schema into the box there to add it straight to the cache and start validating against it without having to upload it to your Iglu Repo for each change.

Let us know if you have any more feature requests!
