### ISSUE TITLE
Inspector isn't working anymore

### ISSUE THREAD

**Issue by JakubFilounek** [snowflake-analytics/chrome-snowplow-inspector#4]
I've been using this amazing tool for several months now and as of today it doesn't work anymore. I visited 2 websites that have properly setup JS tracking codes and both working fine (checked in our system), but the inspector doesn't output anything, it's just blank now.

Chrome version: Version 65.0.3325.146 (Official Build) (64-bit)
Inspector version: 0.2.2

**Comment by jethron** [comment]
Thanks @JakubFilounek, this was a regression introduced in Chrome 65, I've just published a new version which includes a fix for this which should roll out soon.
