### ISSUE TITLE
Tooltips for schema not found

### ISSUE THREAD

**Issue by shermozle** [snowflake-analytics/chrome-snowplow-inspector#5]
Add a tooltip when the schema definition isn't found that includes a link to the options page.

**Comment by jethron** [comment]
Thanks @shermozle, 
As of 0a5b60cc, and release v0.2.3, clicking on the validation panel will now:
- Open the extension options in a new tab when the schema is 'unrecognised'
- Copy any validation errors to the clipboard when an event is 'invalid'
- Copy the schema URL to the clipboard when and event is 'valid'
