### ISSUE TITLE
Can not get custom schema validation to work

### ISSUE THREAD

**Issue by penfold45** [snowflake-analytics/chrome-snowplow-inspector#9]
Hi

I am guess I am doing something wrong but I cannot get this to work. I have added an S3 bucket url that looks something like so. 

https://s3-eu-west-1.amazonaws.com/penfold45-iglu-schemas/ (not real url)

Then in here I have the following directory structure.

schemas/com.penfold45/random_name_here/jsonschema/1-0-0

Then my snowplow code it set up correctly to to post data based on this shema (I am getting the data in to my database).

But the inspector always says "Unrecognised"

The bucket and json file are all public and are def accessible when I go directly to the url.

Any thoughts?

**Comment by jethron** [comment]
Hey @penfold45,

That setup looks OK, have you set the S3 bucket up for CORS as per the [README](https://github.com/snowflake-analytics/chrome-snowplow-inspector/blob/master/README.adoc)?

If you've tried to access the schemas before CORS was enabled, then enabled CORS, Chrome has an annoying habit of caching that the CORS check failed, and will deny access even though you've fixed the issue. The solution seems to be to clear your Chrome cache.

Let me know if this helps!

**Comment by jethron** [comment]
Hi @penfold45, were you able to get this working? Are there any particular steps that aren't clear that could use better documentation?

**Comment by jethron** [comment]
Closing this issue since I can't replicate the issue.
